# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f7f0664be20a5986d4d310b5d736762c2d07c11dd0e0dcca87e0df28f0fcd0f732f1b1bb915eb6b8abdb68b26717d500ac58019311a8e0effed4a548444961a

test:
  secret_key_base: 14546beac1c72cacda93fee446a1d8ed1b2912bb6182981c72ef0bafb8ba3a445737d9df706dfe87a862a58e47c2f3742ffdd07cfcf6044f4f1ccc88095a2342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
